### ISSUE TITLE
The IAM instance profile is not set in the launch template of the ASG

### ISSUE THREAD

**Issue by florent-brosse** [aws-samples/aws-cdk-for-k3scluster#111]
The IAM instance profile is set only in the "Launch configuration" but it's not more used.
The IAM instance profile is not set in the launch template of the ASG.

So the IAM role is not set into the worker node and so the node can not copy files from S3.

**Comment by pahud** [comment]
@florent-brosse 

Thanks for your feedback. I'll open a PR for this.

**Comment by florent-brosse** [comment]
Hi, could you release a new version, please? It makes it easier to test this lib.
Indeed with typescript, it's harder to use a master version of a lib.
```
git clone https://github.com/aws-samples/aws-cdk-for-k3scluster
cd aws-cdk-for-k3scluster
npm install
npm run build
npm link
cd ../myk3scluster-typescript
npm link  cdk-k3s-cluster
```
