### ISSUE TITLE
remove custom resource 

### ISSUE THREAD

**Issue by guan840912** [aws-samples/aws-cdk-for-k3scluster#121]
### Now S3.Bucket native support auto delete object.
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-readme.html#bucket-deletion

example code like this:
```ts
const bucket = new Bucket(this, 'MyTempFileBucket', {
  removalPolicy: RemovalPolicy.DESTROY,
  autoDeleteObjects: true,
});
```

I will use this way to auto delete object and remove custom resource.

**Comment by pahud** [comment]
Great!

**Comment by mreferre** [comment]
I love when we can delete code :)
