### ISSUE TITLE
feat: T4g support

### ISSUE THREAD

**Issue by pahud** [aws-samples/aws-cdk-for-k3scluster#17]
Sounds like a great idea we support the k3s cluster deployment on T4g?

https://aws.amazon.com/tw/blogs/aws/new-t4g-instances-burstable-performance-powered-by-aws-graviton2/

**Comment by mreferre** [comment]
Do you want to do it by simply adding it as an option in the pricing map for now? I know you were looking at removing it longer term.

**Comment by pahud** [comment]
> Do you want to do it by simply adding it as an option in the pricing map for now? I know you were looking at removing it longer term.

OK. Let's add in the map for now. Let me  do it in a separate PR later.

**Comment by UrielCh** [comment]
can a T4g run k3s ?

I tried, but out of the box, an empty k3s server looks to take more than half of a GB memory.

**Comment by mreferre** [comment]
I haven't tested it nor checked memory consumption. Do you expect it to be less? Also, we have hard coded the download of K3s ver 1.16 while, as of today, 1.25 is the latest. Maybe worth trying it?

**Comment by UrielCh** [comment]
I'm now using a more standard AMD64 host with 2Gb Memory.
Moreover, having a public IP not visible on my Ethernet interface was an extra configuration difficulty that In prefers to skip for now.
