### ISSUE TITLE
add s3 Bucket RemovalPolicy 

### ISSUE THREAD

**Issue by guan840912** [aws-samples/aws-cdk-for-k3scluster#7]
add S3 Bucket RemovalPolicy , let `cdk destroy ${stack_name}` can remove it ~~

**Comment by pahud** [comment]
> add S3 Bucket RemovalPolicy , let `cdk destroy ${stack_name}` can remove it ~~

Would you like to have a PR for this?

**Comment by guan840912** [comment]
Yes , I will do it  XD

**Comment by mreferre** [comment]
Thanks for your contribution Neil. I have a few questions (left in the PR).

**Comment by mreferre** [comment]
This has been implemented with this PR: https://github.com/aws-samples/aws-cdk-for-k3scluster/pull/8 

Thanks Neil!
